### ISSUE TITLE
should we normalize the datafit by n_samples as in the lasso benchmark ?

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchmark_mcp#13]
it makes more sense for CV in my opinion (setting of alpha), and since it turns out the features should be normalized for gamma to be easier to set, when we do CV it makes more sense to have the columns standardized than normalized.

@tomMoral @josephsalmon @agramfort

**Comment by agramfort** [comment]
no objection

**Comment by tomMoral** [comment]
no objection either!

**Comment by josephsalmon** [comment]
Good for me too.
And merry christmas!
